
@startuml
title 7的订单退款流程
autonumber

activate 计佣系统

订单系统--> 计佣系统: 监听订单退款的消息

计佣系统-->计佣系统:获取退款数量、退款金额

计佣系统-->计佣系统:根据退款数量判断是不是全退

计佣系统-->计佣系统:查询订单

计佣系统-->计佣系统:根据退款金额计算退款佣金

计佣系统-->计佣系统:更新订单

计佣系统-->]:发MQ计算退佣（订单、skuList、退的佣金、退的数量、是否全退）

deactivate 计佣系统


@enduml