@startuml
autonumber

activate 计佣系统

title 7的订单支付完成流程

订单系统--> 计佣系统: 监听订单支付完成的消息

计佣系统--> OAS:根据订单号查询订单拆分情况（sku实付金额）

return 返回结果

计佣系统-->友家铺子业务中心:获取佣金比例

return 返回结果

计佣系统-->计佣系统:计算sku佣金（保留两位小数）

计佣系统-->计佣系统:存储订单

计佣系统-->]:发MQ计算分佣（订单、skuList、佣金）

deactivate 计佣系统


@enduml