@startuml
autonumber

title pop的订单退款流程

activate 计佣系统

计佣系统-->联盟:每半个小时根据更新时间查询订单

计佣系统-->计佣系统:按订单分组

计佣系统-->计佣系统:根据数据库的退款数量计算退款数量

计佣系统-->计佣系统:判断是不是全退

计佣系统-->计佣系统:根据数据库的退款佣金计算退款佣金

note left
计算公式：所有正向的、逆向的佣金流水计算这个sku的真实退款佣金
end note

计佣系统-->计佣系统:更新订单

计佣系统-->]:发MQ计算退佣（订单、skuList、退的佣金、退的数量、是否全退）

deactivate 计佣系统


@enduml