@startuml
autonumber

title 分佣计佣流程

activate 计佣系统

[--> 计佣系统: 监听分佣计佣消息

计佣系统-->友家铺子业务中心:查询团长分佣比例和上级分佣比例

return 返回结果

计佣系统-->友家铺子业务中心:获取上级pin、自身身份、上级身份

return 返回结果


计佣系统-->计佣系统:计算团长以及上级的分佣（sku佣金汇总成订单的佣金）

note left
计算公式：佣金*分配比例 然后保留两位小数
end note

计佣系统-->计佣系统:存储数据

deactivate 计佣系统


@enduml