@startuml
autonumber

title 退佣流程

activate 计佣系统

[--> 计佣系统: 监听分佣退佣消息


计佣系统-->计佣系统:获取团长佣金以及上级的佣金信息

计佣系统-->计佣系统:计算团长以及上级的退佣（sku佣金汇总成订单的佣金）

note left
计算公式：佣金*分配比例 然后保留两位小数
end note

计佣系统-->计佣系统:更新数据

计佣系统-->]:Mq订单完成推送数据 来源 联盟或者7

deactivate 计佣系统


@enduml