@startuml
autonumber

title 数据同步

activate 生产中心

生产中心--> 生产中心: 生产单号同步 事件是创建生产单号

生产中心--> 生产中心: AO单号同步 事件是调拨完成

生产中心--> 生产中心: AO单状态同步 事件是AO单状态变更

生产中心--> 生产中心: 补货同步生产批次 事件是补货

note left
从租户10到租户1
end note

deactivate 生产中心

@enduml