@startuml
autonumber

title 收货MQ

activate 生产中心

生产中心--> 生产中心: 团长操作一次收货完成

生产中心--> 生产中心: 计算补货数量、更新生产单状态

alt 是否今日收货完成
    生产中心--> 订单中心: 触发待自提 租户1 租户10都发
end

alt 是否全部收货完成
    生产中心--> 生产中心: 收货完成 虚入
end

deactivate 生产中心

@enduml