@startuml
autonumber

title 采购调拨流程

activate 生产中心

生产中心 --> 生产中心: 监听采购调拨消息

alt 是商户生产单

    return 直接返回
end

生产中心 --> 友家铺子: 查询团长信息

note left
团长信息目前不区分租户，租户1和租户10拿到的一样
end note

生产中心 --> 职能部门: 查询门店部门信息

生产中心-->采购系统:创建调拨单

生产中心-->生产中心:落库AO单

alt 是否有关联租户

    生产中心-->]:MQ 同步AO单
end

deactivate 生产中心

@enduml